spring:
  datasource:
    #    type: com.zaxxer.hikari.HikariDataSource
    #    url: jdbc:mysql://localhost:3306/ecomerce?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/ecommerce
    #    username: root
    #    password: 123456789a
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:31395/railway
    username: root
    password: gqXtAoCazieVCyukeAwFNIwhRsVLLFdO

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.cache.use_second_level_cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungsilvertq@gmail.com
    password: mojhffxyqzgdlkkw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OGIzYTlkZWJmZjM0MmY0YWExNGU3NzNmNDNjN2NiMDVkMzFiNjMyNDFiZmYzMjAyZDI0MWE3ZDRlMmE2Y2ZjZWM4YzcxZDFhNWM4YTEwYTMxYzVlNzRiOWFhZDRjOGVlMmE5NGZlYzJlMDFjODFkZjYwNzQ3ZjE4OWVmMzc3Mzg=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  thymeleaf:
    check-template-location: false

#springdoc:
#  api-docs:
#    path: /swagger-ui.html